FROM rstudio/plumber

ADD "water_potability.csv" .

RUN apt-get update -qq && apt-get install -y libssl-dev libcurl4-gnutls-dev libpng-dev libpng-dev pandoc

RUN R -e "install.packages(c('plumber', 'tidyverse', 'ggplot2', 'tidymodels', 'ggpubr','corrplot','caret', 'ranger' ))"

COPY plumber.R plumber.R

EXPOSE 8000

ENTRYPOINT ["R", "-e", \
"pr <- plumber::plumb('plumber.R'); pr$run(host='0.0.0.0', port=8000)"]